version: '3.8'

volumes:
  postgres_volume:

services:
  postgres:
    image: postgres:16-alpine3.23
    container_name: shop-bot-db
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: shopbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U botuser -d shopbot"]
      interval: 5s
      timeout: 5s
      retries: 5

